### ISSUE TITLE
Отчет Ковальчук

### ISSUE THREAD

**Issue by GoogleCodeExporter** [VsMoroz/account-buh-documents#31]
```
Вверху там где Справочники, Помощь. Перед 
Справочники размести новое меню "Отчеты"

Там добавь отчет строчку "Разовые 
Ковальчук И"

Строить его будем по шаблону во вложении, 
сам SQL запрос я напишу завтра.

```

Original issue reported on code.google.com by `rf40...@gmail.com` on 21 Nov 2014 at 4:14

Attachments:
* [2014_11_21_Kovalchuk.ods](https://storage.googleapis.com/google-code-attachments/account-buh-documents/issue-31/comment-0/2014_11_21_Kovalchuk.ods)

**Comment by VsMoroz** [comment]
Отчет Ковальчук, просят добавить в него поле Комментария, я добавил в запрос (посмотри коммит ad10fb3f2aebf54bbd8d69f2a8a85fba8286d73d).
Что бы тебе было удобно поменя в файлике с запросом  имена полей на английские ( которые тебе удобны account-buh-documents/Query/Отчеты - Разовые Ковальчук.sql)

Давай добавим этот запрос в модуль который строит отчет в reestr Отчеты -> Разовые ковальчук, соответственно в документе появится поле коментарий. Шаблон пришлю по email

**Comment by VsMoroz** [comment]
Отчет Ковальчук, просят добавить в него поле Комментария, я добавил в запрос (посмотри коммит ad10fb3f2aebf54bbd8d69f2a8a85fba8286d73d).
Что бы тебе было удобно поменя в файлике с запросом  имена полей на английские ( которые тебе удобны account-buh-documents/Query/Отчеты - Разовые Ковальчук.sql)

Давай добавим этот запрос в модуль который строит отчет в reestr Отчеты -> Разовые ковальчук, соответственно в документе появится поле коментарий. Шаблон пришлю по email

**Comment by panches** [comment]
Изменения выполнил. v1.01.72. Файл выложил

**Comment by VsMoroz** [comment]
Ты похоже не ту версию выложил. Она то лежит в папке 1.01.72 но после установки пишет что она есть 1.01.71 и нового поля в отчете у нее тоже нет.

**Comment by panches** [comment]
заменил на правильную

**Comment by VsMoroz** [comment]
Гуд, работает,  в инсталляционном дистрибутиве сделай заголовок для нового поля Комментарий - таким же по формате как и остальные подзаголовки. Ну и ширину хотя бы на ширину надписи.
Отправляю пользователям  на тестирование.

**Comment by panches** [comment]
Давай это сделаеш ты, а то я опять нитак сделаю (слабо понимая требования). Файл Kovalchuk.xlsx есть установочной папке. Пришли мне его в таком же виде (заголовок и одна пустая строчка).

**Comment by panches** [comment]
файл выложил (с отформатированным файлом)

**Comment by VsMoroz** [comment]
Все гуд, спасибо !

**Comment by VsMoroz** [comment]
Отчет Ковальчук, просят добавить в него поле Статус, разместить его между "Статья бюджета" и "Комментарий". Я добавил значение в запрос,вот этим коммитом 697eb5fe8f7d3450537ffd43759d3c618a24c5f6, 

Давай добавим этот запрос в модуль который строит отчет в reestr Отчеты -> Разовые ковальчук, соответственно в документе появится поле Статус. Шаблон пришлю по email

**Comment by panches** [comment]
Изменения выполнил. v1.01.73. Файл выложил
