### ISSUE TITLE
Отчет Ковальчук ->  Финдеп о утвержденных к оплате счетах

### ISSUE THREAD

**Issue by GoogleCodeExporter** [VsMoroz/account-buh-documents#57]
```
Фиксирую что бы не забыть, опишу детально 
после того как отладим web форму
```

Original issue reported on code.google.com by `rf40...@gmail.com` on 12 Apr 2015 at 9:50

**Comment by VasiliyM** [comment]
Вынес  запрос для формирования документа к финдепу в отдельный файлик.
account-buh-documents/Query/Koval to findep.sql

Добавлю условия:
- что бы в него не попадали счета у который не стоит галочка "реестр koval" , 
- что бы в файлике было видно так же и время когда менеджер подтвердил счет к оплате
- а так же чтобы в него попадали только файлики подтвержденные до 15:00

**Comment by panches** [comment]
Прочитано

**Comment by VasiliyM** [comment]
Изменил запрос, посмотри файлик, может быть тебе поменять названия полей на английские ?
Или ты их поменяй а потом сохрани изменения поставив галочку Create a new branch for this commit and start a pull request  я эти изменения пересмотрю и подтвержу

**Comment by panches** [comment]
Я не могу ничего добавлять в этот файл

**Comment by VsMoroz** [comment]
Смотрю что ты понемногу осваиваешься :) Примени для десктоп приложения для кнопки реетр финдепа, вот этот запрос account-buh-documents/Query/Koval to findep.sql

**Comment by panches** [comment]
А Koval to findep (eng).sql отличается от файла с русскими названиями

**Comment by panches** [comment]
Заменил запрос, v1.01.68
