### ISSUE TITLE
Web Форма для утверждения счетов

### ISSUE THREAD

**Issue by VasiliyM** [VsMoroz/account-buh-documents#58]
Привет ! 

Скрой :
 
Надпись "Выбранным документам присвоить статус"
 Выпадающий список со статусами оплаты
 И кнопку "Применить" 

при выборе Фильтров "Подтвержденные неоплаченные документы" и "Все документы"

Пусть это все будет доступно только если пользователь находится в фильтре"Требуется подтверждение документа"

**Comment by panches** [comment]
выполнил, файл выслал

**Comment by VasiliyM** [comment]
Тестил версию ?
Возникла путаница, ты сделал что бы возможность подтверждать счет была у фильтра:
"Подтвержденные неоплаченные документы"

А нужно что бы такая возможность была только у фильтра: "Требуется подтверждение документа"

**Comment by panches** [comment]
Испрвил
