### ISSUE TITLE
Подтягивать менеджера в форма добавления счета (и разового и ежемесячного)

### ISSUE THREAD

**Issue by VsMoroz** [VsMoroz/account-buh-documents#63]
Добавь в форму добавления счета, что бы после  выбора поля "Клиент" автоматом подтягивалось значение в поле  "Менеджер"

!Внимание - только в форму добавления счетов (и разовых и ежемесячных),  в форму редактирования добавлять не нужно.

**Comment by panches** [comment]
v1.01.69

**Comment by VsMoroz** [comment]
Работает, спасибо

**Comment by VsMoroz** [comment]
Обнаружили ошибку:
Нажать кнопку "Добавить" счет.
Поставить курсор в поле "Клиент"
Захотеть найти там Мировую карту
Начать набирать на клавиатуре Миро (сразу после буквы О) 
Появится ошибка "Не удалось подключиться к MySQL" (жмем ентер)
"ZQuery100: Field 'nik' not found" (жмем ентер)
И в поле "Менеджер" подтягивается менеджер с id = 324

**Comment by panches** [comment]
v1.01.71 исправил ошибку. В БД две одинаковые "Мировые карты" (761, 924) и это равло запрос. Я поставил LIMIT 1 - заработало.

**Comment by VsMoroz** [comment]
Ок, спасибо
