### ISSUE TITLE
Скрывать счета  в web интерфейсе,если стоит галочка "не вкл в реестр ковальчук"

### ISSUE THREAD

**Issue by VsMoroz** [VsMoroz/account-buh-documents#64]
Скрывать счета  в web интерфейсе в фильтре (Требуется подтверждение менеджера), если стоит галочка "не вкл в реестр ковальчук".

**Comment by panches** [comment]
В запрос в поле WHERE добавить проверку z_tab_invoice.not_incl_in_kreestr=0?

**Comment by VsMoroz** [comment]
Да  :)
