### ISSUE TITLE
В инсталляционном пакете создать галочку (по умолчанию включена) "создать ярлык на рабочем столе"

### ISSUE THREAD

**Issue by VsMoroz** [VsMoroz/account-buh-documents#65]
В системе ТТ такая есть, а тут нет :(

**Comment by panches** [comment]
Да, я в курсе. В программе, которая формирует установочный файл под Win 7 нет такой "галочки". Я тут ничег не могу поделать.

**Comment by VsMoroz** [comment]
гм, а в системе ТТ все есть и работает

**Comment by panches** [comment]
Повторю: под Win 7 не работает, под XP - работает. Возможно писатели этой программы подумали, что под семеркой люди не используют "рабочий стол".

**Comment by VsMoroz** [comment]
Установщики в системе ТТ и в реестре разные ? 
В системе ТТ , что под xp что под win 7, 8.1 показывает галочку "создать ярлык на рабочем столе" и выполняет это

**Comment by panches** [comment]
Производитель один и тодже, но версии разные. Один стоит на XP, второй на Семерке.

**Comment by panches** [comment]
Буду искать другой установщик, для решения этой проблемы.

**Comment by panches** [comment]
Нашел другой установщик. Тестовый файл в папке reestr.

**Comment by VsMoroz** [comment]
Да с этим нормально.
Только будет проблема , это ж поставится новая версия, а старая тоже останется у пользователей на компах. Они будут хз какую запускать, если у них ярлык на рабочем столе то новая инсталляха его перезатрет и перезапишет. А если нет то нет

**Comment by panches** [comment]
Что ты предлагаешь? Путь установки (по-умолчанию) я могу изменить.

**Comment by VsMoroz** [comment]
Да давай сделаем путь установки такой же как был у предыдущего установщика

**Comment by panches** [comment]
Сделал. Файл заменил.

**Comment by VsMoroz** [comment]
Гуд , спасибо
