### ISSUE TITLE
Предусмотреть кнопку «Экспорт» для экспорта найденной информации в XLS в виде как есть.

### ISSUE THREAD

**Issue by panches** [VsMoroz/account-buh-documents#66]

**Comment by panches** [comment]
Предлагаю сделать не через кнопу, а через меню: Edit/ to XLS. Данные из таблицы сохраняются в файл export.xls, который будет лежать возле exe файла.
Все это уже работает.

**Comment by panches** [comment]
Сделал так: в меню Edit есть подменю copy, выбрав которое содержание таблицы копируется в буфер обмена (ClipBoard). А дальше Microsoft или OpenOffice ...

**Comment by panches** [comment]
Выполнил, v1.01.74. Файл выложил.

**Comment by VsMoroz** [comment]
Ты применил новый инсталлятор ? 
Он ошибку выдает и не создает ярлый на рабочем столе, хотя галочка стоит.
Не   инсталлит программу.
Удалил  ярлык с рабочего стола и программу с компьютера.

Ошибку отправил почтой

**Comment by panches** [comment]
Использую Inno Script Studio для создания setup.exe.
Проверил (только что на 7-ке) ярлык создается, ошибка не выскакивет.

**Comment by VsMoroz** [comment]
Меня в описании ошибки смутило что инсталлятор говорит что не может найти динамические библиотеки, которые должны быть размещены ... панчес.... :)
На наших компах у пользователей врядли есть такая папка с твоим именем :)
Что нам делать что бы проинсталлить програмку ?

**Comment by panches** [comment]
Файл скачан сегодня?

**Comment by VsMoroz** [comment]
Прям вот только что попробовал все таже ошибка( я тебе отсылал почтой) в ошибке ссылка на папку с динамическими библиотеками и именем панчес в средине этой ссылке.

**Comment by panches** [comment]
Нашел причину ошибки, исправил. Файл выложил.

**Comment by VsMoroz** [comment]
Класс, копируется нормально! 
Отправляю пользователям, неделю заблюдаем за реакцией

**Comment by panches** [comment]
Добавил в отображение два поля: Время счета и Ответственный
v1.01.76

**Comment by VsMoroz** [comment]
Решено, спасибо !
