### ISSUE TITLE
Строка состояния (сумма задолженности, количество строк ...)

### ISSUE THREAD

**Issue by panches** [VsMoroz/account-buh-documents#67]

**Comment by panches** [comment]
Также хотелось бы, чтобы в программе при формировании долгов, суммировалась цифра- на какую сумму долг, а также количество документов, как в базе эксплутации. (то есть внизу приложения сделать строку статуса или просто разместить текст  в которому просуммировать сумму всех счетов отображаемых на экране (пользователь будет выбирать фильтр «бух.задолженности»   система покажет все долговые строки, а строка статуса внизу подсчитает общую сумму) Или пользователь будет строкой поиска фильтровать искомое.

**Comment by panches** [comment]
Выполнил, v1.01.74. Файл выложил.
Однако, при поиске сумма не будет изменяться.

**Comment by panches** [comment]
Теперь и в поиске идет подсчет суммы задолженности.
Версию не менял, файл выложил.

**Comment by VsMoroz** [comment]
Отлично спасибо,  а как считаешь запросом ? Или  приложением ?

**Comment by panches** [comment]
Приложением. Там появилось новое поле "Сумма"

**Comment by VsMoroz** [comment]
Фукнкционал работает.
Только стало медленнее раза в два. Делфи поддерживает многозадачность ? Можно было бы выводить данные в один поток, а сумму подсчитывать во второй.
Тогда бы отображалось на экране быстро, а сумма бы показывалась спустя пару секунд.
А можно ли сумму подсчитывать после выведения на экран ? (тогда можно обойтись без многозадачности)

*Публикую пользователям - наблюдаю за реакцией :)

**Comment by panches** [comment]
В этом исполнении не получится увеличить скорость. 
Можно отдельным запросом считать сумму, НО при поиске сумма считаться не будет.
