### ISSUE TITLE
Просмотр долгов каждого сотрудника, или всего отдела  

### ISSUE THREAD

**Issue by panches** [VsMoroz/account-buh-documents#68]

**Comment by panches** [comment]
Руководителю нужно видеть  долги каждого из своих сотрудников, или хотя бы отдела.  Сейчас в системе видны или персональные долги или вообще все долги. Ты прикинь вариант решения, обсудим ( я сейчас вижу два, нужно выработать самый простой и надежный)

**Comment by panches** [comment]
Давай попробуем обсудить варианты.

**Comment by VsMoroz** [comment]
Предлагаю так:
В меню сверху добавить пункт Настройки.
Там в выпадающем меню пункт Мой отдел, в котором пользователь может поискать ФИО из  списка фамилии всех пользователей из tab_access  у которых tab_access.activated = '1'

Дальше либо ставя галочки либо нажимая кнопку + он выбирает свою команду. Команда сохраняется в локальный файл на компьютере.
Програма анализирует, если команда есть, то в выпадающем верху справа фильтре добавляет пункт: "Бух.задолженность Моего отдела"
Запрос для этого пункта будет таким же как и для  "Бух.задолженность текущего пользователя" только там в поиске где идет отбор по ... = tab_access.id  заменить на  ... IN (id_пользователя, id_участника_отдела1, id_участника_отдела2, итд.)

**Comment by panches** [comment]
Принято, буду реализовывать этот сценарий.

**Comment by panches** [comment]
Выполнил, v1.01.75.
Создал пункт меню, в окне два поля: сотрудники (сдесь выбирать) и отдел. Выбирается щелчком на сотруднике, но и вернуть из отдела щелчком можна. Кнопка Создать и файл и пункт в выпадающем списке создан.
Если нажать кн. Создать и поле Отдел путой, то удаляется файл и пункт в списке.
При загрузке: файл есть - пункт в списке есть и наоборот.
