### ISSUE TITLE
Перенести Web интерфейс с рабочей машины на сервер

### ISSUE THREAD

**Issue by VsMoroz** [VsMoroz/account-buh-documents#70]
Перенести web приложение на сервер для надежности и долговечности

**Comment by VsMoroz** [comment]
10.10.1.2 - получил пользователя.
Новая ссылка http://10.10.1.2/moroz/
Перенес приложение 
Нужно еще увязать аппач с php т.к. не отрабатывают php скрипты.

**Comment by VsMoroz** [comment]
Доменное имя будет такое: http://osdb.datagroup/moroz/

**Comment by panches** [comment]
В reestr паке есть файл setup.ini. Полю host назначь новый адрес и запусти. Запустится, ок. Высылай этот файлик мне. Я могу подставить и выслать, но у меня сомнения есть насчет адреса.

**Comment by VsMoroz** [comment]
Доперенес файлы с паролями о которых говорили по телефону, авторизация проходит, скрипты отрабатывают, открывается главная страница и выдает вот такую ошибку но не показывает элемент выбора менеджера. Данных тоже не показывает. Смотрю что это может быть.

DataTables warning: table id=table_main - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by VsMoroz** [comment]
Почитал ссылку, запустил отладку, действительно как по ссылке и говорят, дебаг браузера показывает что первые два запроса проходят нормально, а потом когда стартует сортировка - выпадает ошибка, (она выпадает на любом из фильтров выбираемых справа вверху). Вобщем нужно бы доработать код что бы не валился при ошибке.
Первую ошибку я сейчас попробую устранить: sort_both.png [HTTP/1.1 404 Not Found 6ms]
Что с второй делать ?

<code>
GET 
XHR 
http://osdb.datagroup/moroz/includes/rassian.json [HTTP/1.1 200 OK 0ms]

POST 
XHR 
http://osdb.datagroup/moroz/files/ajax.sql.combo.php [HTTP/1.1 200 OK 8ms]

GET 
http://osdb.datagroup/moroz/images/sort_both.png [HTTP/1.1 404 Not Found 6ms]

GET 
XHR 
http://osdb.datagroup/moroz/files/main.ajax.php [HTTP/1.1 500 Internal Server Error 13ms]
</code>

**Comment by VsMoroz** [comment]
Браузер в этом запросе 
GET XHR http://osdb.datagroup/moroz/files/main.ajax.php [HTTP/1.1 500 Internal Server Error 13ms]
Спрашивает вот єто:
http://osdb.datagroup/moroz/files/main.ajax.php?action=2&_=1450012882165

**Comment by panches** [comment]
Похоже PHP-запрос не отрабатывает (данные не возвращаются). PHP не настроена.

**Comment by VsMoroz** [comment]
Я бы согласился если бы авторизация не проходила, а она же проходит ! 
Завтра получу доступ к логам  -посмотрим что с той стороны фронтенда

**Comment by VsMoroz** [comment]
На винде (там где все работает) стоит "Apache/2.4.10 (Win32)  PHP/5.4.31"
На Linux стоит "Apache/2.2.16 (Debian), PHP/5.3.3-7+squeeze14"

Изза разности версий в php может такое быть ? У нас вроде код простой... но все же.

**Comment by VsMoroz** [comment]
[Mon Dec 14 10:37:17 2015] [error] PHP Parse error:  syntax error, unexpected '[' in /home/moroz/www/files/main.ajax.php on line 4

**Comment by panches** [comment]
1)Посмотри из-за чего в Apache возникает ошибка 500 Internal Server Error.
2) 4-ая строка в файле main.ajax.php закоментирована. Сравни с файлом на GitHUB
3) разность версий может влиять. Мне так помнится, что в v5.4 были существенные изменеия.

**Comment by VsMoroz** [comment]
4 тая строка не закоментированна: $out = array('data' => []);

<?php
if(!isset($_GET["action"])) {
    //Return result to
    $out = array('data' => []);
    echo json_encode($out); }

**Comment by panches** [comment]
А в файле на GitHUB так

<?php
ini_set('default_charset',"UTF-8");
if(!isset($_GET["action"])) {
    //Return result to

А ругается, т.к. короткий запись массива появился с PHP v5.4.0

**Comment by panches** [comment]
Файл main.ajax.php изменил, ругаться не должно.

**Comment by VsMoroz** [comment]
О, моя версия о разных версиях    php подтвердилась.
Ок, сегодня попробую накатить и посмотрим

**Comment by VsMoroz** [comment]
Перенесено
