### ISSUE TITLE
Ошибка при экспорте в excel. Одна строка разбивается на две. Можно это подправить?

### ISSUE THREAD

**Issue by panches** [VsMoroz/account-buh-documents#72]

**Comment by panches** [comment]
Заменил функцию копирования в буфер обмена, проверяйте.
v1.01.78, файл выложил

**Comment by VsMoroz** [comment]
Чем отличается версия 78 от  79 ?
В хранилище пояледняя это 79

**Comment by panches** [comment]
Посмотри #71

**Comment by panches** [comment]
И еще, мне что-то письма перестали приходить?!

**Comment by VsMoroz** [comment]
Ты не забывай заполнять поле Assignee при создании тикета и тогда будут приходить.
