### ISSUE TITLE
Добавить в систему желаемуя дату оплаты счета и комментарий

### ISSUE THREAD

**Issue by VsMoroz** [VsMoroz/account-buh-documents#73]
Пришел новый финик, новые требования...
Сделаем что можем. 
Просят высокий приоритет у этой задачи
!! Важно, web часть будем выполнять под более старую версию php PHP/5.3.3-7+squeeze14 которая работает на linux сервере.

Срок подтверждения счета до 12:00 
Добавим поле "Плановая дата оплаты".
Может быть добавим поле "Примечание менеджера
Изменим немного отчет для финдепа. 
Буду сегодян здесь описывать задачу по частям.

**Comment by VsMoroz** [comment]
Добавляем поле для  плановой даты оплаты счета
ALTER TABLE `z_tab_invoice` ADD `dt_plan_of_pay` DATE NOT NULL DEFAULT '0000-00-00' COMMENT 'Ожидаем оплату к' AFTER `client` 

На web страничке создаем два новых элемента, первый "Оплатить к:" с календарем:
Значение поля "Оплатить к:" переключается в момент когда выбирают статус подтверждения к оплате : 
- по умолчанию  = (+ 14 дней от сегодня)
- при  выборе статуса с id=20 (он же Срочно в оплату) = (следующий рабочий день, тоесть нужно будет если сегодня пятница ставить понедельник)
  -  при  выборе статуса с id=10 (он же Подтвержден к оплате) = (+ 14 дней от сегодня) 
  - если пользователь захочет он выберет стаус оплаты, затем поменяет значение в поле "Оплатить к:" и затем нажмет кнопку "Подтвердить".

Второй элемент Примечание: все что здесь менеджер напишет, при нажатии кнопки "Подтвердить"  нужно будет добавить в поле z_tab_invoice.description  не затирая того что там есть, методом конкатенации:

UPDATE `klients`.`z_tab_invoice` SET `description` = CONCAT(description,', добавляемый текст') WHERE `z_tab_invoice`.`id` =89;

Элементы "Оплатить к:" и "ввода Примечания" предлагаю разместить ниже элемента в котором мы выбираем срочность оплаты.
Если что потом подвинем.

**Comment by panches** [comment]
Поля добавил, функционал настроил и работает.
Куда эти поля расположить пока не вижу. Пока расположены хаотически.

p.s. на поле "Плановая дата оплаты" наверно надо поставить проверку?

**Comment by VsMoroz** [comment]
Да на плановые нужно установить проверку, выставляемая дата не может быть меньше или равна сегодня.

**Comment by panches** [comment]
Добавил проверку ввода даты

**Comment by VsMoroz** [comment]
Сделай для  срочных еще такую функцию:
 Если сотрудник выбрал статус срочно, то элемент с календариком получает значение и становится неактивным для редактирования, что бы сотрудник не мог менять ничего.

А дата оплаты в календарике выставлялась вот как:
- если статус срочно выбран когда системное время < 12:00  тогда дата +1 рабочий день
- если статус срочно выбран когда системное время => 12:00 тогда в календарик вносится +2 рабочих дня (не забудь про пятницы и субботы)

**Comment by panches** [comment]
Добавил функционал.

**Comment by VsMoroz** [comment]
Первое изменение в приложении: 
- Меняем отчет строящийся по кнопке "Реестр для фин.депа", меняем шаблон findep.xlsx (лежит в папке с программой) после столбца "Комент" добавлены два новых столбца, выслал файл тебе в почту.  
- меняем запрос которым мы строим этот отчет, вот коммит: b9fb5975ec109c86d26a9a1c865d1e5b6a5a60ef

**Comment by panches** [comment]
Выполнил, v1.01.80

**Comment by VsMoroz** [comment]
Добавь в приложение, в разовые и ежемесячные, в форму добавления и редактирования счета поле Желаемая дата оплаты  z_tab_invoice.dt_plan_of_pay элемент пусть будет такой же календарик как для аналогичных датовых полей в этой форме.
Значения по умолчанию нет ( у нас так же сделанно и с другими полями даты в этой форме)

Так же добавь что бы когда счет подтверждается из приложения (правый щелчек мыши на счете) при выборе происходило такое действие:
- Статусы -> Подтвержден к оплате (так же в поле dt_plan_of_pay ставилась дата сегодня +14 дней)
- Статусы -> Срочно в оплату (так же в поле dt_plan_of_pay ставилась дата следующего рабочего дня )

**Comment by VsMoroz** [comment]
По элементам добавленным в web форму, сделай дату в виде календарика - это возможно ? 
Так же дату сделай в понятном для пользователя виде, ДД.ММ.ГГ (сейчас она выглядит как ГГГГ-ММ-ДД)

**Comment by panches** [comment]
Выполнил, v1.01.81

**Comment by VsMoroz** [comment]
1.01.81 пока еще нет в гуглдрайве.
По web интерфейсу  можно задействовать элементы jquery, смотрел ? 
Например http://jqueryui.com/datepicker/

**Comment by panches** [comment]
Уже доступен. Последнее время подвисает гуглдрайве.
Я больше склоняюсь к bootstrap-datepicker https://github.com/eternicode/bootstrap-datepicker

**Comment by VsMoroz** [comment]
bootstrap-datepicker - подходит.
В десктоп приложении - нет возможности удалить желаемую дату оплаты, желательно что бы такая возможность была (можно рядом маленькой кнопкой с крестиком) если обычным способом(выделить и нажать кнопку делейт) - невозможно.

**Comment by VsMoroz** [comment]
Еще поправка в вот этом техзадании, ниже приведенный запрос нужно выполнять только если элемент веб формы в котором вносится примечание - НЕ ПУСТОЙ.

> Второй элемент Примечание: все что здесь менеджер напишет, при нажатии кнопки "Подтвердить" нужно будет добавить в поле z_tab_invoice.description не затирая того что там есть, методом конкатенации:
> 
> UPDATE klients.z_tab_invoice SET description = CONCAT(description,', добавляемый текст') WHERE z_tab_invoice.id =89;

А то в конечный файл вставляются запятые, некрасиво

**Comment by panches** [comment]
Выполнил:
1. Календарик виден вовсех браузерах (IE, firefox, Opera, Chrome). Проверял.
2. Поле description заполняется, если Примечание не пустое.

**Comment by VsMoroz** [comment]
Ух я смотрю на этот коммит 6c0e9732738a9722e7ef99d7f8a80a7e858ff954 ты не отдельные файлы апдейтишь, а вообще все заливаешь заново ?

**Comment by panches** [comment]
Основные файлы я не удалял, только добавляю нужные.

**Comment by VsMoroz** [comment]
Последний коммит с 117 измененными файлами  with 4,089 additions and 282 deletions
Ты их все 117 поправил  ? :)

**Comment by panches** [comment]
Эти файлы относятся к новому календарику.

**Comment by VsMoroz** [comment]
После реализации datapicker основной функционал тестировал ? 
Делаю так: выбираю счет, выбираю оплату срочно (скрипт подставляет дату в датапикер), нажимаю Применить всплывает окошко "Дату необходимо выбрать" Видать скрипт не совсем корректно подставляет дату в датапикер.

С несрочной оплатой та же история.

А так же если сначала выставить не срочность платежа, а затем в календарике вручную выбрать дату - то все равно  пишет что "Дату необходимо выбрать"

**Comment by panches** [comment]
Это мой недосмотр, исправил.

**Comment by VsMoroz** [comment]
Добавь еще в WEB форму что бы после каждого нажатияк кнопки Подтвердить, после выполнения всех запросов, происходила очистка содержимого в элементе в который вводится примечание.

**Comment by VsMoroz** [comment]
Привет ! Измени плиз запрос которым строится отчет по кнопке "Реестр для фин.депа"
dc7f534e9430a42105a38f1c6a445b1c9593c055

То что ниже уже поправил ? :

> В десктоп приложении - нет возможности удалить желаемую дату оплаты, желательно что бы такая возможность была (можно рядом маленькой кнопкой с крестиком) если обычным способом(выделить и нажать кнопку делейт) - невозможно.

**Comment by panches** [comment]
Привет! 
Запрос заенил,  желаемую дату оплаты можно удалиьметодом: выделить и нажать кнопку делейт
Версию не менял (v1.01.81)

**Comment by panches** [comment]
Поле Примечание очищается, проверял.

**Comment by VsMoroz** [comment]
Модернизируем отчет строящийся по меню Отчеты->Разовые Ковальчук 
В ексель файлик в конце добавляем поле срок оплаты по договору/счету (файлик вышлю почтой), в поле вносить значения из запроса 026431b9b18638ac461bc1b8a65c95be0515eac2 из добавленного поля  dtplanpay

**Comment by panches** [comment]
Выполнил, v1.01.82

**Comment by VsMoroz** [comment]
Спасибо работает, отправил на продуктивное тестирование.

**Comment by VsMoroz** [comment]
Тест пройден, закрываю
