### ISSUE TITLE
Добавить возможность очистить поле Дата оплаты в формах редактирования разовых и ежемесячных счетов

### ISSUE THREAD

**Issue by VsMoroz** [VsMoroz/account-buh-documents#74]
Выявили что если дата оплаты счета была проставленна(ошибочно) то нет возможности из десктоп приложения ее удалить и счет числится оплаченным.

Прошу добавить возможность очистить поле Дата оплаты в формах редактирования разовых и ежемесячных счетов. Интуитивней всего кнопкой делейт или бекспейс с клавиатуры

**Comment by panches** [comment]
выполнил, v1.01.84

**Comment by VsMoroz** [comment]
Спасибо
