### ISSUE TITLE
Добавить поле "Дата регистрации"  в отчет по разовым документам

### ISSUE THREAD

**Issue by VsMoroz** [VsMoroz/account-buh-documents#76]
В отчет разовые Ковальчук нужно добавить поле "Дата регистрации" вставить его после поля "Статья бюджета"

Возьмем его из поля z_tab_invoice.timestamp в формате ДД.ММ.ГГГГ
Готовлю запрос и шаблон отчета.

**Comment by panches** [comment]
Выполнил, v1.01.86 (Запрос и шаблон подправил).

**Comment by VsMoroz** [comment]
В ексель файле заголовок поля Дата регистрации сделай в формате переносить по словам и уменьши его ширину как раз до размеров слова "регистрации"  И в целом все.

**Comment by panches** [comment]
Выполнил

**Comment by VsMoroz** [comment]
Спасибо, все нормально
