### ISSUE TITLE
Добавить кнопку "удалить" в формы редактирования Счета, Акта и НН, в разовые и ежемесячные

### ISSUE THREAD

**Issue by VsMoroz** [VsMoroz/account-buh-documents#77]
Привет ! 
Доставим пару последних штрихов, прошу добавить кнопку "удалить" в формы редактирования Счета, Акта и НН, в разовые и ежемесячные.

При нажатии на нее удалять это документ. 
- ( по позже сделаем что бы документ не удалялся, а помечался как удаленный, но пока пусть удаляется)

**Comment by panches** [comment]
выполнил, v1.01.88

**Comment by VsMoroz** [comment]
Перенеси плиз кнопку с самого права, в левую часть и давай на ней заменить пиктограмку на какую то другую, ну например с минусом. А то сейчас на ней пиктограмка с крестиком, пользователь легко может перепутать ее с копкой отмена.

**Comment by VsMoroz** [comment]
Перенеси плиз кнопку с самого права, в левую часть и давай на ней заменим пиктограмку на какую то другую, ну например с минусом. А то сейчас на ней пиктограмка с крестиком, пользователь легко может перепутать ее с копкой отмена, которая тоже с крестиком..

**Comment by panches** [comment]
Кнопку перенес, иконку заменил, v1.01.89

**Comment by VsMoroz** [comment]
Что то не срабатывает кнопка "редактирование" при выборе селектора в режим "Акт"

**Comment by panches** [comment]
А в этой записи "Акт" есть?

**Comment by VsMoroz** [comment]
Да, все гуд.
